/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodosDetailsRouteImport } from './routes/todosDetails-route'
import { Route as RootRouteImport } from './routes/root-route'
import { Route as IndexRouteImport } from './routes/index-route'
import { Route as EditTodoRouteImport } from './routes/editTodo-route'
import { Route as AddTodoRouteImport } from './routes/addTodo-route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TodosDetailsRouteRoute = TodosDetailsRouteImport.update({
  path: '/todosDetails-route',
  getParentRoute: () => rootRoute,
} as any)

const RootRouteRoute = RootRouteImport.update({
  path: '/root-route',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/index-route',
  getParentRoute: () => rootRoute,
} as any)

const EditTodoRouteRoute = EditTodoRouteImport.update({
  path: '/editTodo-route',
  getParentRoute: () => rootRoute,
} as any)

const AddTodoRouteRoute = AddTodoRouteImport.update({
  path: '/addTodo-route',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/addTodo-route': {
      preLoaderRoute: typeof AddTodoRouteImport
      parentRoute: typeof rootRoute
    }
    '/editTodo-route': {
      preLoaderRoute: typeof EditTodoRouteImport
      parentRoute: typeof rootRoute
    }
    '/index-route': {
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/root-route': {
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRoute
    }
    '/todosDetails-route': {
      preLoaderRoute: typeof TodosDetailsRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AddTodoRouteRoute,
  EditTodoRouteRoute,
  IndexRouteRoute,
  RootRouteRoute,
  TodosDetailsRouteRoute,
])

/* prettier-ignore-end */
